name: cypress test with cucumber

on:
    push:
        branches: [master]

jobs:
    Run_test:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                node-version: [14.17.0]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"   
            - run: npm i npm@latest
            - run: npm i
            - name: run test
              run: npm run runOnChrome
            - name: Generate Report
              if: always()
              run: npm run generateReport
            - name: Upload Results
              uses: actions/upload-artifact@v1
              if: always()
              with:
                name: cucumber.html
                path: ./reports
                   
            - name: Publishing cucumber.html artifact to Github Actions
              uses: actions/upload-artifact@v2
              if: always()
              with:
                 name: cucumber.html
                 path: reports       
            - name: Deploy report
              uses: JamesIves/github-pages-deploy-action@4.1.4
              if: always()
              with:
               branch: master 
               folder: reports 
                
